repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Prefeitura-Lagoa-da-Prata
repo_name: Prefeitura de Lagoa da Prata
site_name: Prefeitura Municipal de Lagoa da Prata


markdown_extensions:
  - md_in_html
  - pymdownx.extra
  - attr_list
  - pymdownx.magiclink

plugins:
  - search
  - open-in-new-tab

nav:
  - Início: index.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Cronograma Planejado: planejamento/cronograma_planejado.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Processos de Design: planejamento/processos_de_design.md
    - Ferramentas do Projeto: planejamento/ferramentas_do_projeto.md
    - Metodologia: planejamento/metodologia.md
    - Sites Avaliados: planejamento/sites_avaliados.md    
    - Site Escolhido: planejamento/site_escolhido.md
  - Reuniões:
    - Reunião 1: reunioes/reuniao_1.md
    - Reunião 2: reunioes/reuniao_2.md
    - Reunião 3: reunioes/reuniao_3.md
    - Reunião 4: reunioes/reuniao_4.md
  - Apresentações:
    - Apresentação 1: apresentacoes/apresentacao1.md
    - Apresentação 2: apresentacoes/apresentacao2.md
    - Apresentação 3: apresentacoes/apresentacao3.md
    - Apresentação 4: apresentacoes/apresentacao4.md
    - Apresentação 5: apresentacoes/apresentacao5.md 
    - Apresentação 6.1: apresentacoes/apresentacao6.1.md 
  - Análise de requisitos I:
    - Aspectos Éticos: requisitos1/aspectos-eticos.md
    - Questionario: requisitos1/questionario.md
    - Entrevista: requisitos1/entrevista.md
    - Perfil do Usuário: requisitos1/perfil-do-usuario.md
    - Personas: requisitos1/personas.md
    - Cenários: requisitos1/cenarios.md
    - Análise de Tarefas: requisitos1/analise-tarefas.md
  - Análise de requisitos II:
      - Principios Gerais: requisitos2/principios_gerais.md
      - Metas de Usabilidade: requisitos2/metas-usabilidade.md
      - Guias de Estilo: requisitos2/guia-de-estilo.md
      - Caracteristicas da Plataforma Para o Projeto: requisitos2/caracteristicas.md
  - Design Nível 1: 
    - Analise de Tarefas:
      - Planejamento da Avaliação da Analise de Tarefas: design/Nivel_1/analise_tarefas/Pl_avaliacao_tarefas.md
      - Planejamento do Relato dos Resultados da Analise de Tarefas: design/Nivel_1/analise_tarefas/Pl_relatoresultado_tarefas.md
      - Relato de Resultados da Analise de Tarefas: design/Nivel_1/analise_tarefas/relatoresultado_tarefas.md
    - Storyboard:
      - Planejamento da Avaliação do Storyboard: design/Nivel_1/storyboard/Pl_avaliacao_storyboard.md
      - Planejamento do Relato dos Resultados do Storyboard: design/Nivel_1/storyboard/Pl_relato_storyboard.md
      - Relato de Resultados para Storyboards: design/Nivel_1/storyboard/relato_resultados_storyboard.md
  - Design Nível 2:
    - Planejamento da Avaliação de Prototipação de Papel: design/Nivel_2/prototipo_papel/Pl_avaliacao.md
    - Planejamento do Relato de Resultados da Prototipação de Papel: design/Nivel_2/prototipo_papel/Pl_relato_resultados.md
    - Relato dos resultados do Protótipo de Papel: design/Nivel_2/prototipo_papel/relato_resultados.md
  - Design Nível 3:
    - Planejamento da Avaliação de Prototipação de Alta Fidelidade: design/Nivel_3/pl_avaliacao_prototipo.md
    - Planejamento do Relato de Resultados da Prototipação de Alta Fidelidade: design/Nivel_3/pl_relato_resultados.md
  - Verificação:
    - Verificação Grupo 06:
      - Introdução: verificacao/grupo06/introducao.md
      - Etapa 2: 
        - Planejamento: verificacao/grupo06/etapa2/planejamento.md
        - Verificação:  verificacao/grupo06/etapa2/verificacao.md
      - Etapa 3: 
        - Planejamento: verificacao/grupo06/etapa3/planejamento.md
        - Verificação:  verificacao/grupo06/etapa3/verificacao.md
      - Etapa 4:       
        - Planejamento: verificacao/grupo06/etapa4/planejamento.md
        - Verificação:  verificacao/grupo06/etapa4/verificacao.md
      - Etapa 5: 
        - Planejamento: verificacao/grupo06/etapa5/planejamento.md
        - Verificação:  verificacao/grupo06/etapa5/verificacao.md
    - Verificacão do Grupo 05:
      - Etapa 2:
        - Planejamento: verificacao/grupo/etapa2/planejamento.md
        - Verificação Cenários: verificacao/grupo/etapa2/cenarios.md
      - Etapa 3:
        - Planejamento: verificacao/grupo/etapa3/planejamento.md
        - Verificação Metas: verificacao/grupo/etapa3/metas-de-usabilidade.md
        - Verificação Caracteristicas: verificacao/grupo/etapa3/caracteristicas-gerais.md
        - Verificação Principios: verificacao/grupo/etapa3/principios-gerais.md
      - Etapa 4:
        - Planejamento: verificacao/grupo/etapa4/planejamento.md
        - Verificação Planejamento da Avaliação da Análise de Tarefas: verificacao/grupo/etapa4/planejamento_avali_analise_tarefas copy.md
        - Verificação Planejamento do Relato de resultados da Análise de Tarefas: verificacao/grupo/etapa4/planejamento_relato_analise_tarefas.md
        - Verificação do Relato de resultados da Análise de Tarefas: verificacao/grupo/etapa4/resultado_analise_tarefas.md
        - Verificação Planejamento da Avaliação do StoryBoard: verificacao/grupo/etapa4/planejamento_avali_storyboard.md
        - Verificação do Relato de resultados do StoryBoard: verificacao/grupo/etapa4/resultado_storyboard.md
      - Etapa 5:
        - Planejamento: verificacao/grupo/etapa5/planejamento.md
        - Verificação Planejamento da avaliação do Protótipo de Papel: verificacao/grupo/etapa5/planejamento_avali_prot_papel.md
        - Verificação Planejamento do Relato de resultados do Protótipo de Papel: verificacao/grupo/etapa5/planejamento_relato_prototipo_papel.md
      - Etapa 7:
        - Planejamento: verificacao/grupo/etapa7/planejamento.md
        - Verificação Planejamento da avaliação do Prototipação de Alta Fidelidade: verificacao/grupo/etapa7/planejamento_avali_prot_alta.md
        - Verificação Planejamento do Relato de Resultados da Prototipação de Alta Fidelidade: verificacao/grupo/etapa7/planejamento_relato_prototipo_alta.md




theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  langage: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Trocar pro modo escuro
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Trocar pro modo claro
      primary: teal
      accent: teal

    

